name: master-database

services:
  sql_receptionist:
    build:
      target: prod
      args:
        LIBCYAML_VARIANT: release
    networks:
      - cloudflared
      - postgres

  create_tables:
    networks:
      - postgres

  cloudflared:
    working_dir: /apps/cloudflared
    build:
      context: ../
      dockerfile: apps/cloudflared/Dockerfile
    environment:
      TZ: America/Toronto
      TUNNEL_TOKEN_FILE: /run/secrets/cloudflared_token
    entrypoint: /entrypoint.sh
    restart: unless-stopped
    secrets:
      - cloudflared_token
    networks:
      - cloudflared

  # @TODO secrets for db authentication
  postgres:
    networks:
      - postgres

networks:
  cloudflared:
    name: cloudflared
  postgres:
    name: postgres
    driver: bridge

secrets:
  cloudflared_token:
    file: ${SECRETS_DIR}/master-database/cloudflared-cloudflare-token.txt
