name: master-database

services:
  test:
    working_dir: /apps/tests
    build:
      context: ../
      dockerfile: apps/tests/Dockerfile
    secrets:
      - admin
    depends_on:
      postgres:
        condition: service_healthy
      sql_receptionist:
        condition: service_started

  # @TODO secrets for db authentication
  postgres:
    restart: no
    environment:
    volumes:
      - ${UNIVERSAL_CONFIG_DIR}/master-database/postgres/postgresql.dev.conf:/etc/postgresql/postgresql.conf:ro
      - ${UNIVERSAL_CONFIG_DIR}/master-database/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro

secrets:
  admin:
    file: ${SECRETS_DIR}/admin.txt
