name: master-database

services:
  sql_receptionist:
    build:
      target: dev
      args:
        LIBCYAML_VARIANT: debug
    env_file:
      - path: ${UNIVERSAL_CONFIG_DIR}/.env.dev
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/master-database/.env.dev
        required: true
    develop:
      watch:
        - action: sync+restart
          path: ./../apps/sql-receptionist
          target: ./apps/sql-receptionist
          initial_sync: true
        - action: sync+restart
          path: ${UNIVERSAL_CONFIG_DIR}/config.yml
          target: /config.yml
          initial_sync: true
    networks:
      - wywy_website_master_database-sql_receptionist
      - default
    # compile and run the application.
    # Do not close the container on error.
    command: bash -c "make clean && make && exec valgrind --leak-check=yes --show-leak-kinds=definite ./app"

  create_tables:
    env_file:
      - path: ${UNIVERSAL_CONFIG_DIR}/.env.dev
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/master-database/.env.dev
        required: true
    develop:
      watch:
        - action: sync+restart
          path: ${UNIVERSAL_CONFIG_DIR}/config.yml
          target: /apps/create_tables/config.yml
          initial_sync: true
        - action: sync+restart
          path: ./../apps/create_tables
          target: ./apps/create_tables
          initial_sync: true

  # @TODO secrets for db authentication
  postgres:
    build:
      context: ../
      dockerfile: apps/postgres/Dockerfile
      target: db
    restart: always
    env_file:
      - path: ${UNIVERSAL_CONFIG_DIR}/.env.dev
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/backup/.env.dev
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/master-database/.env.dev
        required: true

networks:
  default: {}
  wywy_website_master_database-sql_receptionist:
    name: wywy_website_master_database-sql_receptionist
