name: master-database

services:
  test:
    working_dir: /apps/tests
    build:
      context: ../
      dockerfile: apps/tests/Dockerfile
    env_file:
      - path: ${UNIVERSAL_CONFIG_DIR}/.env
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/.env.dev
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/master-database/.env
        required: true
      - path: ${UNIVERSAL_CONFIG_DIR}/master-database/.env.dev
        required: true
    secrets:
      - admin
    volumes:
      - ./../apps/tests:/apps/tests
      - ${UNIVERSAL_CONFIG_DIR}/config.yml:/config.yml
    depends_on:
      postgres:
        condition: service_healthy
      sql_receptionist:
        condition: service_started

  # @TODO secrets for db authentication
  postgres:
    restart: no
    environment:
      PGDATA: /tmp/postgres
    volumes:
      - ${UNIVERSAL_CONFIG_DIR}/master-database/postgres/postgresql.dev.conf:/etc/postgresql/postgresql.conf:ro
      - ${UNIVERSAL_CONFIG_DIR}/master-database/postgres/pg_hba.conf:/etc/postgresql/pg_hba.conf:ro

secrets:
  admin:
    file: ${SECRETS_DIR}/admin.txt
