FROM gcc:15-trixie AS builder
WORKDIR /apps/sql-receptionist

ENV LD_LIBRARY_PATH=/usr/local/lib

COPY ./apps/sql-receptionist .

RUN apt-get update && apt-get install -y \
    libpq-dev \
    libyaml-dev \
    wget \
    bzip2 \
    valgrind \
    gnupg \
    # @TODO verification with gnupg
    # QoL
    gdb \
    nano
RUN wget https://github.com/akheron/jansson/releases/download/v2.14.1/jansson-2.14.1.tar.bz2 \
    && bunzip2 -c jansson-2.14.1.tar.bz2 | tar xf - \
    && cd jansson-2.14.1 \
    && ./configure \
    && make \
    && make check \
    && make install

RUN wget https://github.com/tlsa/libcyaml/archive/refs/tags/v1.4.2.tar.gz \
    && tar -xvzf v1.4.2.tar.gz \
    && cd libcyaml-1.4.2 \
    && make \
    && make install VARIANT=debug

EXPOSE 2523

CMD ["./app"]