apiVersion: v1
kind: ConfigMap
metadata:
  name: master-database-service-config
  labels:
    app: master-database
immutable: true
data:
  SQL_RECEPTIONIST_HOST: "sql-receptionist"
  USER_ID: "25231"
  SYNC_STATUS: "true"
  DATABASE_HOST: "db.internal"
  DATABASE_PORT: "5432"
  DATABASE_USERNAME: "postgres"
  # SQL receptionist verbosity
  SQL_RECEPTIONIST_LOG_QUERIES: "TRUE"
  SQL_RECEPTIONIST_LOG_INPUT: "TRUE"
  SQL_RECEPTIONIST_LOG_ENDPOINT_TRIGGERS: "TRUE"
  SQL_RECEPTIONIST_LOG_SCHEMA_FAILURES: "FALSE"
  SQL_RECEPTIONIST_LOG_REQUESTS: "FALSE"
  SQL_RECEPTIONIST_LOG_RESPONSES: "FALSE"
  SQL_RECEPTIONIST_SEARCH_LIMIT: "10"
