apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: master-database

resources:
  - configmap-common.yaml
  - configmap-service.yaml
  - sql-receptionist-deployment.yaml
  - service.yaml
  - db-setup.yaml
