name: Deploy

on:
  push:
    branches: [dev]

permissions:
  packages: write

jobs:
  build-push:
    runs-on: [self-hosted, wywy, dind]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push sql-receptionist image
        run: |
          docker build \
            --target prod \
            --build-arg USER_ID=25231 \
            -t ghcr.io/wywysenarios/master-db/sql-receptionist:dev \
            -f apps/sql-receptionist/Dockerfile .
          docker push ghcr.io/wywysenarios/master-db/sql-receptionist:dev

      - name: Build and push create_tables image
        run: |
          docker build \
            --build-arg USER_ID=25231 \
            -t ghcr.io/wywysenarios/master-db/create_tables:dev \
            -f apps/create_tables/Dockerfile .
          docker push ghcr.io/wywysenarios/master-db/create_tables:dev
