name: Deploy

on:
  push:
    branches: [dev-k8s]

permissions:
  packages: write

jobs:
  build-push:
    runs-on: [self-hosted, wywy, dind]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Login to ghcr.io
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io \
            -u "${{ github.actor }}" --password-stdin

      - name: Build and push sql-receptionist image
        run: |
          docker build \
            --target prod \
            --build-arg USER_ID=25231 \
            -t ghcr.io/wywysenarios/master-db/sql-receptionist:dev \
            -f apps/sql-receptionist/Dockerfile .
          docker push ghcr.io/wywysenarios/master-db/sql-receptionist:dev

      - name: Build and push create_tables image
        run: |
          docker build \
            --build-arg USER_ID=25231 \
            -t ghcr.io/wywysenarios/master-db/create_tables:dev \
            -f apps/create_tables/Dockerfile .
          docker push ghcr.io/wywysenarios/master-db/create_tables:dev
